force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick-Off</fullName>
            </value>
            <value>
                <fullName>Start</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/updateStage.cls
public with sharing class updateStage {
    public updateStage() {
        List<Project__c> projectsInPreKickOff= [SELECT Id, Status__c FROM Project__c WHERE Status__c = 'Pre Kick-Off'];
        List<Project__c> updatedProjects= new List<Project__c>();
        
        for(Project__c project: projectsInPreKickOff){
            project.Status__c= 'Start';
            updatedProjects.add(project); 
        }
        update updatedProjects;
    }   
}