force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick-Off</fullName>
            </value>
            <value>
                <fullName>Start</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/recordTypes/Projects.recordType-meta.xml
<RecordType>
    <fullName>Projects</fullName>
    <active>true</active>
    <label>Projects</label>
</RecordType>

force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <description>Information on the hours that should be covered</description>
    <label>ProjectsLineItem</label>
    <nameField>
        <label>ProjectLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectsLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/Covered__c.field-meta.xml
<CustomField>
    <fullName>Covered__c</fullName>
    <formula>QuantityHours__c  &gt;=  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Covered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>ProjectsLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectsTrigger.cls
public with sharing class ProjectsTrigger {

    public static void beforeUpdate(Map<Id, Project__c> newProjectsById, Map<Id, Project__c> oldProjectsById) {

        //Tomamos los mapas de projects recibidos por parámetro
        //y nos quedamos sólo con aquellos cuyo Status cambió a 'Started'
        Set<Id> startedProjects = new Set<Id>();
        for (Project__c project : newProjectsById.values()) {
            if (project.Status__c == 'Start' && oldProjectsById.get(project.Id).Status__c != 'Start') {
            	startedProjects.add(project.Id);
            }
        }

        //traemos la lista de projectItems pertenecientes a los projects que pasaron a started
        List<ProjectLineItem__c> projectItems = [SELECT Id, Covered__c, Project__c, Project__r.Project_Manager__r.Email FROM ProjectLineItem__c
                                                 WHERE Project__c IN :startedProjects];

    	//Creamos un map donde key=projectId, value=lista de projectItems correspondientes
    	Map<Id, List<ProjectLineItem__c>> itemsByProjectId = new Map<Id, List<ProjectLineItem__c>>();

        //se completa el map
        for (ProjectLineItem__c item : projectItems) {
            if (!itemsByProjectId.containsKey(item.Project__c)) {
                itemsByProjectId.put(item.Project__c, new List<ProjectLineItem__c>{item});
            }
            else itemsByProjectId.get(item.Project__c).add(item);
        }
        
        //recorremos los items de cada project y buscamos que TODOS tengan su campo covered__c = true
        for (Id projectId : startedProjects) {
            Boolean fail = false;
            String email = itemsByProjectId.get(ProjectId)[0].Project__r.Project_Manager__r.Email;
            
            //fail si algún item NO está cubierto
            for (ProjectLineItem__c projectItem : itemsByProjectId.get(projectId)) {
                if (!projectItem.Covered__c) fail = true;
            	break;
            }
            if (fail) newProjectsById.get(projectId).addError('Project unable to be updated to Start status');
            
            //fail si falta SquadLead
            if (oldProjectsById.get(projectId).Squad_Lead__c == null) newProjectsById.get(projectId).addError('Project unable to be updated to Start status');

        }
    }
}