force-app/main/default/objects/AllocatedResource__c/AllocatedResource__c.object-meta.xml
<CustomObject>
    <description>Information about the responsibility of a user in a project</description>
    <label>AllocatedResource</label>
    <nameField>
        <label>AllocatedResource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AllocatedResources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AllocatedResource__c/fields/ProjectsItem__c.field-meta.xml
<CustomField>
    <fullName>ProjectsItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProjectsItem</label>
    <referenceTo>ProjectLineItem__c</referenceTo>
    <relationshipName>AllocatedResources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AllocatedResource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource(User)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AllocatedResources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <description>Information on the hours that should be covered</description>
    <label>ProjectsLineItem</label>
    <nameField>
        <label>ProjectLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectsLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/Covered__c.field-meta.xml
<CustomField>
    <fullName>Covered__c</fullName>
    <formula>QuantityHours__c  &gt;=  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Covered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>ProjectsLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity(Hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/QuantityHours__c.field-meta.xml
<CustomField>
    <fullName>QuantityHours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Covered hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectDataService.cls
public with sharing class ProjectDataService {
    
    //método para traernos los roles con horas pendientes en un project__c
    @AuraEnabled(Cacheable=true)
    public static List<ProjectLineItem__c> getPendingRoles(Id projectId) {
        return [SELECT Id, Role__c, Quantity__c, QuantityHours__c
                FROM ProjectLineItem__c
                WHERE Project__c = :projectId AND Covered__c = false];        
    }
    
    //método para traernos los recursos libres fuera de las fechas pasadas como parámetro
    @AuraEnabled(Cacheable=true)
    public static List<User> getFreeResources(Date startDate, Date endDate) {
        return [SELECT Id, Name, UserRole.Name
                FROM User
                WHERE Id NOT IN (SELECT Resource__c
                                 FROM AllocatedResource__c
                                 WHERE ((Start_Date__c >= :startDate AND Start_Date__c <= :endDate) OR //empieza durante el proyecto
                                        (End_Date__c >= :startDate AND End_Date__c <= :endDate) OR     //termina durante el proyecto
                                        (Start_Date__c <= :startDate AND End_Date__c >= :endDate)))];  //empieza y termina fuera del proyecto
    }
    
    //método para traernos los recursos libres fuera de las fechas pasadas como parámetro
    @AuraEnabled(Cacheable=true)
    public static List<User> getFreeResourcesByRole(Date startDate, Date endDate, String role) {
        return [SELECT Id, Name, UserRole.Name
                FROM User
                WHERE UserRole.Name = :role AND Id NOT IN (SELECT Resource__c
                                                           FROM AllocatedResource__c
                                                           WHERE ((Start_Date__c >= :startDate AND Start_Date__c <= :endDate) OR //empieza durante el proyecto
                                                                  (End_Date__c >= :startDate AND End_Date__c <= :endDate) OR     //termina durante el proyecto
                                                                  (Start_Date__c <= :startDate AND End_Date__c >= :endDate)))];  //empieza y termina fuera del proyecto
    }
    
    //método para insertar registros en el objeto AllocatedResource (asignar recursos)
    @AuraEnabled(Cacheable=true)
    public static void assignResource(List<Object> newJSONAllocatedResources) {

            System.debug(newJSONAllocatedResources);
            List<Object> objectList = (List<Object>) newJSONAllocatedResources;
            List<AllocatedResource__c> newAllocatedResourcesList = new List<AllocatedResource__c>();

            for (Object obj : objectList) {
                Map<String, Object> objectMap = (Map<String, Object>) obj;
                AllocatedResource__c newResource = new AllocatedResource__c();
                newResource.Resource__c = (Id)objectMap.get('Resource__c');
                newResource.ProjectsItem__c = (Id)objectMap.get('ProjectsItem__c');
                newAllocatedResourcesList.add(newResource);
            }
        
		insert newAllocatedResourcesList;

        //System.debug('hola');
        //System.debug(newAllocatedResources);
        //insert newAllocatedResources;

    }
    
}