force-app/main/default/objects/OpportunityLineItem__c/OpportunityLineItem__c.object-meta.xml
<CustomObject>
    <label>OpportunityLineItem</label>
    <nameField>
        <label>OpportunityLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OpportunityLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityLineItem__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>OpportunityLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>Product Owner</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre Kick-Off</fullName>
            </value>
            <value>
                <fullName>Start</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/ProjectLineItem__c.object-meta.xml
<CustomObject>
    <description>Information on the hours that should be covered</description>
    <label>ProjectsLineItem</label>
    <nameField>
        <label>ProjectLineItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProjectsLineItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectLineItem__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>ProjectsLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProjectLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity(Hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OpportunitiesTest.cls
@isTest
public class OpportunitiesTest {
    
	@isTest
    public static void OpportunitiesUpdateTest() {
        
        Integer bulkQuantity = 21;
        List<Opportunity> oppList = new List<Opportunity>();
        List<OpportunityLineItem__c> oppLineItemList = new List<OpportunityLineItem__c>();
        
        //creamos un bulk de Opportunities
        for (Integer i = 0; i < bulkQuantity; i++) {
            
            Opportunity opp = new Opportunity();
            opp.Name = 'This is a test';
            opp.Start_Date__c = Date.today();
            opp.End_Date__c = Date.today().addDays(50);
            opp.CloseDate = Date.today();
            opp.StageName = 'Negotiation/Review';
            oppList.add(opp);
            
            //Para cada opportunity, creamos 3 items
            for (Integer j = 0; j < 3; j++) {
                OpportunityLineItem__c oppLineItem = new OpportunityLineItem__c();
                oppLineItem.Opportunity__r = opp;
                
                if (Math.mod(j, 3) == 0) {
                	oppLineItem.Roles__c = 'Consultant';
                    oppLineItem.Quantity__c = 10;
                }
                else if (Math.mod(j, 3) == 1) {
                	oppLineItem.Roles__c = 'Developer';
                    oppLineItem.Quantity__c = 15;
                } 
                else if (Math.mod(j, 3) == 2) {
                	oppLineItem.Roles__c = 'Testing';
                    oppLineItem.Quantity__c = 6;
                }
				oppLineItemList.add(oppLineItem);
            }
        }
        insert oppList;
        
        //recorremos los oppLineItemList para actualizar su relación con la Opp
        for (OpportunityLineItem__c item : oppLineItemList) {
            item.Opportunity__c = item.Opportunity__r.Id;
        }
        insert oppLineItemList;
        
        //ahora actualizamos la Stage de las Opp a 'Closed Won' y disparamos el trigger
        for (Opportunity opp : oppList) {
            opp.StageName = 'Closed Won';
        }
        update oppList;
        
        //chequear creación de nuevos Project__c con información proveniente de las opp
        List<Project__c> newProjectsList =  [SELECT Id, Opportunity__c, Status__c, End_Date__c, Hours__c FROM Project__c WHERE Name = 'This is a test'];
        Project__c newProject = newProjectsList[0];
        
        system.assertEquals(newProject.Opportunity__c, oppList[0].Id);
        system.assertEquals(newProject.Status__c, 'Pre Kick-Off');
        system.assertEquals(newProject.End_Date__C, oppList[0].End_Date__c);
        system.assertEquals(newProject.Hours__c, 31);
        
        //chequear creación de nuevos ProjectItem__c asociados a los Project__c 
        system.assertEquals(3, [SELECT count() FROM ProjectLineItem__c WHERE Project__r.Id = :newProject.Id]);
    }
}